language: node_js
node_js:
  - 6
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - python-pip
      - git

      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip
      - bazel

before_install:
  - git submodule update --init

install:
  - bash tools/configure.sh
  - cd third-party/tensorflow && bazel build --verbose_failures --config=opt //tensorflow:libtensorflow.so && cd ../..
  - npm i

script: npm run build

cache:
  directories:
    - node_modules
    - third-party
