language: node_js
node_js:
  - 6
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - python-pip
      - git

      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip

before_script:
  - npm i
  - git submodule update --init

script: npm run build

cache:
  directories:
    - node_modules
