language: node_js
node_js:
  - 6
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - python-pip
      - gcc
      - git

before_script:
  - npm i
  - git submodule --init update

script: npm run build

cache:
  directories:
    - node_modules
